familytrivia/config/routes.rb
Rails.application.routes.draw do
  resources :rounds do
    resources :questions

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

familytrivia/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

familytrivia/app/models/question.rb
class Question < ApplicationRecord
    belongs_to :round
end

familytrivia/app/models/round.rb
class Round < ApplicationRecord
  has_many :questions
  validates :questions, length: { maximum: 10,
    too_long: "%{count} questions is the maximum amount" }
end

familytrivia/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

familytrivia/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

    def index 
        @questions = Question.all
    end

    def new
        @question = Round.questions.new
    end
end

familytrivia/app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
    before_action :find_round, only: [:show, :update, :destroy, :edit]
    
    def index
        @rounds = Round.all 
    end
    
    def show
        @round = Round.find(params[:id])
    end

    def new
        @round = Round.new
    end

    def create
        @round = Round.new(round_params)
        if @round.save
            redirect_to '/rounds'
        else
            render "rounds/New"
        end
    end

    
    def edit
    end
    
    def update
    end

    def destroy
        @round = Round.find(params[:id])
        @round.destroy
        redirect_to "/rounds"
    end

    private
    def round_params
        params.require(:round).permit(:round_name)
    end
    
    def find_round
        @round = Round.find(params[:id])
    end
end

familytrivia/app/helpers/application_helper.rb
module ApplicationHelper
end

familytrivia/app/helpers/questions_helper.rb
module QuestionsHelper
end

familytrivia/app/helpers/rounds_helper.rb
module RoundsHelper
end

familytrivia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Familytrivia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

familytrivia/app/views/questions/edit.html.erb
<%= render 'partials/menu' %>

<h2>Please edit now</h2>


<input type="hidden" value="<%=form_authenticity_token %>" name="authenticity_token" />

<%= form_with model: @question do |f| %>
<ol>
    <li>
        <%= f.text_field :question %>
        <%= f.text_field :answer %>
        <%= f.number_field :points, in: 1.0..10.0, step: 0.5 %>
    </li>
    
  </ol>
  <%= f.submit "Finish Editing" %>
<% end %>

</form>

familytrivia/app/views/questions/index.html.erb
<h1> Hello </h1>

familytrivia/app/views/questions/new.html.erb
<h2>Please enter a single question below</h2>

familytrivia/app/views/questions/show.html.erb
<h2> Question<%= @question.id %> </h2> 
<ol>
    <li>
        <%= @question["question"] %> <%= @question["answer"] %> <%= @question["points"] %>
    </li>
</ol>

familytrivia/app/views/rounds/edit.html.erb
<h1> Round <%= @round.round_name %> </h1>

familytrivia/app/views/rounds/index.html.erb
<h1>Rounds#Index</h1>
<p>Hello World </p>
<p><%= link_to "Create Your Own", new_round_url %></p>

<% @rounds.each do |round| %>
<%= round[:round_name] %> <%= link_to "Show", round_url(round[:id]) %> <%= link_to "Edit", edit_round_url(round[:id])%>
<%= link_to 'Delete This', round_url(round[:id]),
              method: :delete,
              data: { confirm: 'Thankyou, Next!' } %><br>
<% end %>      

familytrivia/app/views/rounds/new.html.erb
<h1>Rounds#New</h1>

<h2> Please enter a name for your round and some questions to populate it </h2>
<form action="/rounds" method="POST">
<input type="hidden" value="<%=form_authenticity_token %>" name="authenticity_token"/>

<%= form_with model: @round do |r| %>
<%= r.text_field :round_name, :required => true %>
<%= r.submit "Name Round" %>
<% end %>

familytrivia/app/views/rounds/show.html.erb
<h1> Round <%= @round.round_name %> </h1>
<%= link_to "Create some questions", new_round_question_path(@round, @question) %>
<p>
<% @round.questions.each do |q| %>
<%= q.question %> <br>
<% end %></p>